

export const S = {
    // Pattern
    emailValidationPattern: /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/iu,
    userNamePattern: /^[aA-zZ\s аА-яЯ\s \d]+$/,
    phoneMaskPattern: ['+', /\d/, ' ', '(', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
    bankCardMaskPattern: [/\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/],
    bankCardExpiryDateMaskPattern: [/\d/, /\d/, '/', /\d/, /\d/],

    // Input error message
    emailNotValid: 'Invalid email address',
    phoneNumberNotValid: 'Invalid phone number',
    inputRequired: 'Required field',
    passwordNotValid: 'Password is incorrect',
    passwordMinimum: 'Minimum 8 characters',
    userNameExistError: 'This username is already taken, please choose another',
    userNameSymbolExclude: 'Name must not contain the following characters: < > \ " % ; ( ) &',

    // Role for sign up
    Contractor: 'Contractor',
    Singer: 'Singer',
    Musician: 'Musician',
    Band: 'Band',
    // Sort by
    SortByOptions: {
        dropHeader: 'Sort by',
        dropOptions: [
            'Sort by',
            'Best Match',
            'Rating',
            'Most Popular'
        ]
    },
    // Currency type 
    currencyTypes: [
        {
            shortCurrencyValue: 'USD-$',
            fullCurrencyValue: 'United States dollar - $',
        },
        {
            shortCurrencyValue: 'CAD-$',
            fullCurrencyValue: 'Canadian dollar - $',
        },
        {
            shortCurrencyValue: 'EUR-€',
            fullCurrencyValue: 'Euro - €',
        },
        {
            shortCurrencyValue: 'GBP-£',
            fullCurrencyValue: 'British pound - £',
        },
        {
            shortCurrencyValue: 'JMD-$',
            fullCurrencyValue: 'Jamaican dollar - $',
        },
    ],
    // Account tabs
    AccountTabs: {
        contractorTabs: [
            "Personal Info",
            "Payments and Payouts",
            "Change Password",
            "Notification",
            "My Ads",
            "Terms of Service",
        ],
        musicianTabs: [
            "Personal Info",
            "Payments and Payouts",
            "Change Password",
            "Notification",
            "Terms of Service",
        ],
    },
    // Sign up
    PositionOptions: {
        dropHeader: 'Choose your position',
        dropOptions: [
            'Event Coordinator',
            "Restaurant Manager",
            "Talent Acquisition",
            "Corporate Talent Acquisition",
            "Music Director",
            "Organization Leader",
            "Other",
        ]
    },
    Instruments: [
        "Accordion",
        "Balalaika",
        "Cello",
        "Cymbals",
        "Clarinet",
        "Drum",
        "Flute",
        "Grand piano",
        "Harp",
        "Organ",
        "Piano",
        "Saxophone",
        "Synthesizer",
        "Violin",
        "Bagpipe",
        "Bassoon",
        "Baton",
        "Chamber music",
        "Contrabass",
        "Horn",
        "Marimba",
        "Oboe",
        "Guitar",
        "Trumpet",
        "Tuba",
        "Contrabass",
        "Viola",
        "Percussion",
        "Trombone",
        "Wind group",
    ],
    Genres: [
        "Jazz",
        "Hip-Hop",
        "Electronic",
        "Rock",
        "Disco",
        "Fusion",
        "Pop",
        "Folk",
        "Rap",
        "Blues",
        "Reggae",
        "Indie",
        "Classical",
        "Funk",
        "Latin",
        "Techno",
        "Country",
    ],
    bandMembers: [
        "Bassist",
        "Cellist",
        "Conductor",
        "DJ",
        "Drummer",
        "Flautist",
        "Guitarist",
        "Organist",
        "Pianist",
        "Pop star",
        "Rapper",
        "Saxophonist",
        "Trumpeter",
        "Trombonist",
        "Keyboard player",
        "Violinist",
        "Singer",
    ],
    SignUpContentContractor: [
        {
            tabNumber: 1,
            fullNumber: 4,
            title: 'Welcome to MuzNet!',
            text: 'Please, pick a username',
            progressWidth: 15
        },
        {
            tabNumber: 2,
            fullNumber: 4,
            title: 'Welcome to MuzNet!',
            text: 'Select profile type according to your needs',
            progressWidth: 32
        },
        {
            tabNumber: 3,
            fullNumber: 4,
            title: 'Welcome to MuzNet!',
            text: 'Select profile position',
            progressWidth: 60
        },
        {
            tabNumber: 4,
            fullNumber: 4,
            title: 'Welcome to MuzNet!',
            text: 'Lets add profile information',
            progressWidth: 100
        },
    ],
    SignUpContentMusician: [
        {
            tabNumber: 1,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Please, pick a username',
            progressWidth: 15
        },
        {
            tabNumber: 2,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Select profile type according to your needs',
            progressWidth: 32
        },
        {
            tabNumber: 3,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Select profile type according to your needs',
            progressWidth: 50
        },
        {
            tabNumber: 4,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Please choose your musical instrument',
            progressWidth: 65
        },
        {
            tabNumber: 5,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Please choose your music genres',
            progressWidth: 85
        },
        {
            tabNumber: 6,
            fullNumber: 6,
            title: 'Welcome to MuzNet!',
            text: 'Lets add profile information',
            progressWidth: 100
        },
    ],
    SignUpContentBand: [
        {
            tabNumber: 1,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Please, pick a username',
            progressWidth: 14
        },
        {
            tabNumber: 2,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Select profile type according to your needs',
            progressWidth: 28
        },
        {
            tabNumber: 3,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Select profile type according to your needs',
            progressWidth: 42
        },
        {
            tabNumber: 4,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Please, choose group members',
            progressWidth: 56
        },
        {
            tabNumber: 5,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Please choose your musical instrument',
            progressWidth: 70
        },
        {
            tabNumber: 6,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Please choose your music genres',
            progressWidth: 84
        },
        {
            tabNumber: 7,
            fullNumber: 7,
            title: 'Welcome to MuzNet!',
            text: 'Lets add profile information',
            progressWidth: 100
        },
    ],
    ListOfWorldCountries: [
        'Afghanistan',
        'Albania',
        'Algeria',
        'American Samoa',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas, The',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'British Virgin Islands',
        'Brunei Darussalam',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cayman Islands',
        'Central African Republic',
        'Chad',
        'Channel Islands',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo, Dem. Rep.',
        'Congo, Rep.',
        'Costa Rica',
        "Cote d'Ivoire",
        'Croatia',
        'Cuba',
        'Curacao',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt, Arab Rep.',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini',
        'Ethiopia',
        'Faroe Islands',
        'Fiji',
        'Finland',
        'France',
        'French Polynesia',
        'Gabon',
        'Gambia, The',
        'Georgia',
        'Germany',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland',
        'Grenada',
        'Guam',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Honduras',
        'Hong Kong SAR, China',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran, Islamic Rep.',
        'Iraq',
        'Ireland',
        'Isle of Man',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        "Korea, Dem. People's Rep.",
        'Korea, Rep.',
        'Kosovo',
        'Kuwait',
        'Kyrgyz Republic',
        'Lao PDR',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macao SAR, China',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia, Fed. Sts.',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Caledonia',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'North Macedonia',
        'Northern Mariana Islands',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Romania',
        'Russian Federation',
        'Rwanda',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Sint Maarten (Dutch part)',
        'Slovak Republic',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'St. Kitts and Nevis',
        'St. Lucia',
        'St. Martin (French part)',
        'St. Vincent and the Grenadines',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Syrian Arab Republic',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkiye',
        'Turkmenistan',
        'Turks and Caicos Islands',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela, RB',
        'Vietnam',
        'Virgin Islands (U.S.)',
        'West Bank and Gaza',
        'Yemen, Rep.',
        'Zambia',
        'Zimbabwe',
    ]

}
