

export const S = {
    // Pattern
    emailValidationPattern: /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/iu,
    phoneMaskPattern: ['+', /\d/, ' ', '(', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],

    // Input error message
    emailNotValid: 'Invalid email address',
    phoneNumberNotValid: 'Invalid phone number',
    inputRequired: 'Required field',
    passwordNotValid: 'Password is incorrect',
    passwordMinimum: 'Minimum 8 characters',
    userNameExistError: 'This username is already taken, please choose another',
    userNameSymbolExclude: 'Name must not contain the following characters: < > \ " % ; ( ) &',

    // Role for sign up
    Contractor: 'Contractor',
    Singer: 'Singer',
    Musician: 'Musician',
    Band: 'Band',

    PositionOptions: {
        dropHeader: 'Choose your position',
        dropOptions: [
            'Event Coordinator',
            "Restaurant Manager",
            "Talent Acquisition",
            "Corporate Talent Acquisition",
            "Music Director",
            "Organization Leader",
            "Other",
        ]
    },
    Instruments: [
        "Accordion",
        "Balalaika",
        "Cello",
        "Cymbals",
        "Clarinet",
        "Drum",
        "Flute",
        "Grand piano",
        "Harp",
        "Organ",
        "Piano",
        "Saxophone",
        "Synthesizer",
        "Violin",
        "Bagpipe",
        "Bassoon",
        "Baton",
        "Chamber music",
        "Contrabass",
        "Horn",
        "Marimba",
        "Oboe",
        "Guitar",
        "Trumpet",
        "Tuba",
        "Contrabass",
        "Viola",
        "Percussion",
        "Trombone",
        "Wind group",
    ],
    Genres: [
        "Jazz",
        "Hip-Hop",
        "Electronic",
        "Rock",
        "Disco",
        "Fusion",
        "Pop",
        "Folk",
        "Rap",
        "Blues",
        "Reggae",
        "Indie",
        "Classical",
        "Funk",
        "Latin",
        "Techno",
        "Country",
    ],
    bandMembers: [
        "Bassist",
        "Cellist",
        "Conductor",
        "DJ",
        "Drummer",
        "Flautist",
        "Guitarist",
        "Organist",
        "Pianist",
        "Pop star",
        "Rapper",
        "Saxophonist",
        "Trumpeter",
        "Trombonist",
        "Keyboard player",
        "Violinist",
        "Singer",
    ]

}
